// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
  numberOfOrders: number;
  paidOrders: number;
  numberOfClients: number;
  numbersOfProducts: number;
  productsWithInventory: number;
  lowInventory: number;
  notPaidOrders: number;
}
